version: "3"
services:
  collecta:
    build: ../.
    restart: always
    links:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:example@db/collecta?sslmode=disable
    volumes:
      - $PWD/config:/etc/collecta
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: collecta

  portal:
    image: steveltn/https-portal:1
    restart: always
    ports:
      - '80:80'
      - '443:443'
    links:
      - collecta
    environment:
      DOMAINS: 'core.collecta.site -> http://collecta:8080'
      STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'