version: "3"
services:
  collecta:
    build: ../.
    links:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:example@db/collecta?sslmode=disable
    volumes:
      - $PWD/config:/etc/collecta
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: collecta
