// Code generated by entc, DO NOT EDIT.

package question

import (
	"github.com/minskylab/collecta/ent/schema"
)

const (
	// Label holds the string label denoting the question type in the database.
	Label = "question"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHash holds the string denoting the hash vertex property in the database.
	FieldHash = "hash"
	// FieldTitle holds the string denoting the title vertex property in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description vertex property in the database.
	FieldDescription = "description"
	// FieldMetadata holds the string denoting the metadata vertex property in the database.
	FieldMetadata = "metadata"
	// FieldValidator holds the string denoting the validator vertex property in the database.
	FieldValidator = "validator"
	// FieldAnonymous holds the string denoting the anonymous vertex property in the database.
	FieldAnonymous = "anonymous"

	// Table holds the table name of the question in the database.
	Table = "questions"
	// AnswersTable is the table the holds the answers relation/edge.
	AnswersTable = "answers"
	// AnswersInverseTable is the table name for the Answer entity.
	// It exists in this package in order to avoid circular dependency with the "answer" package.
	AnswersInverseTable = "answers"
	// AnswersColumn is the table column denoting the answers relation/edge.
	AnswersColumn = "question_answers"
	// InputTable is the table the holds the input relation/edge.
	InputTable = "inputs"
	// InputInverseTable is the table name for the Input entity.
	// It exists in this package in order to avoid circular dependency with the "input" package.
	InputInverseTable = "inputs"
	// InputColumn is the table column denoting the input relation/edge.
	InputColumn = "question_input"
	// FlowTable is the table the holds the flow relation/edge.
	FlowTable = "questions"
	// FlowInverseTable is the table name for the Flow entity.
	// It exists in this package in order to avoid circular dependency with the "flow" package.
	FlowInverseTable = "flows"
	// FlowColumn is the table column denoting the flow relation/edge.
	FlowColumn = "flow_questions"
)

// Columns holds all SQL columns for question fields.
var Columns = []string{
	FieldID,
	FieldHash,
	FieldTitle,
	FieldDescription,
	FieldMetadata,
	FieldValidator,
	FieldAnonymous,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Question type.
var ForeignKeys = []string{
	"flow_questions",
}

var (
	fields = schema.Question{}.Fields()

	// descTitle is the schema descriptor for title field.
	descTitle = fields[2].Descriptor()
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator = descTitle.Validators[0].(func(string) error)

	// descAnonymous is the schema descriptor for anonymous field.
	descAnonymous = fields[6].Descriptor()
	// DefaultAnonymous holds the default value on creation for the anonymous field.
	DefaultAnonymous = descAnonymous.Default.(bool)
)
