// Code generated by entc, DO NOT EDIT.

package ip

const (
	// Label holds the string label denoting the ip type in the database.
	Label = "ip"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the ip in the database.
	Table = "i_ps"
)

// Columns holds all SQL columns for ip fields.
var Columns = []string{
	FieldID,
}
