// Code generated by entc, DO NOT EDIT.

package flow

import (
	"github.com/minskylab/collecta/ent/schema"
)

const (
	// Label holds the string label denoting the flow type in the database.
	Label = "flow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldState holds the string denoting the state vertex property in the database.
	FieldState = "state"
	// FieldStateTable holds the string denoting the statetable vertex property in the database.
	FieldStateTable = "state_table"
	// FieldPastState holds the string denoting the paststate vertex property in the database.
	FieldPastState = "past_state"
	// FieldInputs holds the string denoting the inputs vertex property in the database.
	FieldInputs = "inputs"

	// Table holds the table name of the flow in the database.
	Table = "flows"
	// QuestionsTable is the table the holds the questions relation/edge.
	QuestionsTable = "questions"
	// QuestionsInverseTable is the table name for the Question entity.
	// It exists in this package in order to avoid circular dependency with the "question" package.
	QuestionsInverseTable = "questions"
	// QuestionsColumn is the table column denoting the questions relation/edge.
	QuestionsColumn = "flow_questions"
)

// Columns holds all SQL columns for flow fields.
var Columns = []string{
	FieldID,
	FieldState,
	FieldStateTable,
	FieldPastState,
	FieldInputs,
}

var (
	fields = schema.Flow{}.Fields()

	// descStateTable is the schema descriptor for stateTable field.
	descStateTable = fields[2].Descriptor()
	// StateTableValidator is a validator for the "stateTable" field. It is called by the builders before save.
	StateTableValidator = descStateTable.Validators[0].(func(string) error)
)
