// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/google/uuid"
	"github.com/minskylab/collecta/ent/account"
	"github.com/minskylab/collecta/ent/predicate"
	"github.com/minskylab/collecta/ent/user"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	_type        *account.Type
	sub          *string
	remoteID     *string
	secret       *string
	clearsecret  bool
	owner        map[uuid.UUID]struct{}
	clearedOwner bool
	predicates   []predicate.Account
}

// Where adds a new predicate for the builder.
func (au *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	au.predicates = append(au.predicates, ps...)
	return au
}

// SetType sets the type field.
func (au *AccountUpdate) SetType(a account.Type) *AccountUpdate {
	au._type = &a
	return au
}

// SetSub sets the sub field.
func (au *AccountUpdate) SetSub(s string) *AccountUpdate {
	au.sub = &s
	return au
}

// SetRemoteID sets the remoteID field.
func (au *AccountUpdate) SetRemoteID(s string) *AccountUpdate {
	au.remoteID = &s
	return au
}

// SetSecret sets the secret field.
func (au *AccountUpdate) SetSecret(s string) *AccountUpdate {
	au.secret = &s
	return au
}

// SetNillableSecret sets the secret field if the given value is not nil.
func (au *AccountUpdate) SetNillableSecret(s *string) *AccountUpdate {
	if s != nil {
		au.SetSecret(*s)
	}
	return au
}

// ClearSecret clears the value of secret.
func (au *AccountUpdate) ClearSecret() *AccountUpdate {
	au.secret = nil
	au.clearsecret = true
	return au
}

// SetOwnerID sets the owner edge to User by id.
func (au *AccountUpdate) SetOwnerID(id uuid.UUID) *AccountUpdate {
	if au.owner == nil {
		au.owner = make(map[uuid.UUID]struct{})
	}
	au.owner[id] = struct{}{}
	return au
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (au *AccountUpdate) SetNillableOwnerID(id *uuid.UUID) *AccountUpdate {
	if id != nil {
		au = au.SetOwnerID(*id)
	}
	return au
}

// SetOwner sets the owner edge to User.
func (au *AccountUpdate) SetOwner(u *User) *AccountUpdate {
	return au.SetOwnerID(u.ID)
}

// ClearOwner clears the owner edge to User.
func (au *AccountUpdate) ClearOwner() *AccountUpdate {
	au.clearedOwner = true
	return au
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (au *AccountUpdate) Save(ctx context.Context) (int, error) {
	if au._type != nil {
		if err := account.TypeValidator(*au._type); err != nil {
			return 0, fmt.Errorf("ent: validator failed for field \"type\": %v", err)
		}
	}
	if au.sub != nil {
		if err := account.SubValidator(*au.sub); err != nil {
			return 0, fmt.Errorf("ent: validator failed for field \"sub\": %v", err)
		}
	}
	if len(au.owner) > 1 {
		return 0, errors.New("ent: multiple assignments on a unique edge \"owner\"")
	}
	return au.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccountUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccountUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   account.Table,
			Columns: account.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: account.FieldID,
			},
		},
	}
	if ps := au.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value := au._type; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  *value,
			Column: account.FieldType,
		})
	}
	if value := au.sub; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: account.FieldSub,
		})
	}
	if value := au.remoteID; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: account.FieldRemoteID,
		})
	}
	if value := au.secret; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: account.FieldSecret,
		})
	}
	if au.clearsecret {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: account.FieldSecret,
		})
	}
	if au.clearedOwner {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.OwnerTable,
			Columns: []string{account.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.owner; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.OwnerTable,
			Columns: []string{account.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	id           uuid.UUID
	_type        *account.Type
	sub          *string
	remoteID     *string
	secret       *string
	clearsecret  bool
	owner        map[uuid.UUID]struct{}
	clearedOwner bool
}

// SetType sets the type field.
func (auo *AccountUpdateOne) SetType(a account.Type) *AccountUpdateOne {
	auo._type = &a
	return auo
}

// SetSub sets the sub field.
func (auo *AccountUpdateOne) SetSub(s string) *AccountUpdateOne {
	auo.sub = &s
	return auo
}

// SetRemoteID sets the remoteID field.
func (auo *AccountUpdateOne) SetRemoteID(s string) *AccountUpdateOne {
	auo.remoteID = &s
	return auo
}

// SetSecret sets the secret field.
func (auo *AccountUpdateOne) SetSecret(s string) *AccountUpdateOne {
	auo.secret = &s
	return auo
}

// SetNillableSecret sets the secret field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableSecret(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetSecret(*s)
	}
	return auo
}

// ClearSecret clears the value of secret.
func (auo *AccountUpdateOne) ClearSecret() *AccountUpdateOne {
	auo.secret = nil
	auo.clearsecret = true
	return auo
}

// SetOwnerID sets the owner edge to User by id.
func (auo *AccountUpdateOne) SetOwnerID(id uuid.UUID) *AccountUpdateOne {
	if auo.owner == nil {
		auo.owner = make(map[uuid.UUID]struct{})
	}
	auo.owner[id] = struct{}{}
	return auo
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableOwnerID(id *uuid.UUID) *AccountUpdateOne {
	if id != nil {
		auo = auo.SetOwnerID(*id)
	}
	return auo
}

// SetOwner sets the owner edge to User.
func (auo *AccountUpdateOne) SetOwner(u *User) *AccountUpdateOne {
	return auo.SetOwnerID(u.ID)
}

// ClearOwner clears the owner edge to User.
func (auo *AccountUpdateOne) ClearOwner() *AccountUpdateOne {
	auo.clearedOwner = true
	return auo
}

// Save executes the query and returns the updated entity.
func (auo *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	if auo._type != nil {
		if err := account.TypeValidator(*auo._type); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"type\": %v", err)
		}
	}
	if auo.sub != nil {
		if err := account.SubValidator(*auo.sub); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"sub\": %v", err)
		}
	}
	if len(auo.owner) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"owner\"")
	}
	return auo.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	a, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return a
}

// Exec executes the query on the entity.
func (auo *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AccountUpdateOne) sqlSave(ctx context.Context) (a *Account, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   account.Table,
			Columns: account.Columns,
			ID: &sqlgraph.FieldSpec{
				Value:  auo.id,
				Type:   field.TypeUUID,
				Column: account.FieldID,
			},
		},
	}
	if value := auo._type; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  *value,
			Column: account.FieldType,
		})
	}
	if value := auo.sub; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: account.FieldSub,
		})
	}
	if value := auo.remoteID; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: account.FieldRemoteID,
		})
	}
	if value := auo.secret; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: account.FieldSecret,
		})
	}
	if auo.clearsecret {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: account.FieldSecret,
		})
	}
	if auo.clearedOwner {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.OwnerTable,
			Columns: []string{account.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.owner; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.OwnerTable,
			Columns: []string{account.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	a = &Account{config: auo.config}
	_spec.Assign = a.assignValues
	_spec.ScanValues = a.scanValues()
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return a, nil
}
