// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/google/uuid"
	"github.com/minskylab/collecta/ent/contact"
	"github.com/minskylab/collecta/ent/person"
)

// ContactCreate is the builder for creating a Contact entity.
type ContactCreate struct {
	config
	mutation *ContactMutation
	hooks    []Hook
}

// SetName sets the name field.
func (cc *ContactCreate) SetName(s string) *ContactCreate {
	cc.mutation.SetName(s)
	return cc
}

// SetValue sets the value field.
func (cc *ContactCreate) SetValue(s string) *ContactCreate {
	cc.mutation.SetValue(s)
	return cc
}

// SetKind sets the kind field.
func (cc *ContactCreate) SetKind(c contact.Kind) *ContactCreate {
	cc.mutation.SetKind(c)
	return cc
}

// SetNillableKind sets the kind field if the given value is not nil.
func (cc *ContactCreate) SetNillableKind(c *contact.Kind) *ContactCreate {
	if c != nil {
		cc.SetKind(*c)
	}
	return cc
}

// SetPrincipal sets the principal field.
func (cc *ContactCreate) SetPrincipal(b bool) *ContactCreate {
	cc.mutation.SetPrincipal(b)
	return cc
}

// SetValidated sets the validated field.
func (cc *ContactCreate) SetValidated(b bool) *ContactCreate {
	cc.mutation.SetValidated(b)
	return cc
}

// SetFromAccount sets the fromAccount field.
func (cc *ContactCreate) SetFromAccount(b bool) *ContactCreate {
	cc.mutation.SetFromAccount(b)
	return cc
}

// SetNillableFromAccount sets the fromAccount field if the given value is not nil.
func (cc *ContactCreate) SetNillableFromAccount(b *bool) *ContactCreate {
	if b != nil {
		cc.SetFromAccount(*b)
	}
	return cc
}

// SetID sets the id field.
func (cc *ContactCreate) SetID(u uuid.UUID) *ContactCreate {
	cc.mutation.SetID(u)
	return cc
}

// SetOwnerID sets the owner edge to Person by id.
func (cc *ContactCreate) SetOwnerID(id uuid.UUID) *ContactCreate {
	cc.mutation.SetOwnerID(id)
	return cc
}

// SetOwner sets the owner edge to Person.
func (cc *ContactCreate) SetOwner(p *Person) *ContactCreate {
	return cc.SetOwnerID(p.ID)
}

// Save creates the Contact in the database.
func (cc *ContactCreate) Save(ctx context.Context) (*Contact, error) {
	if _, ok := cc.mutation.Name(); !ok {
		return nil, errors.New("ent: missing required field \"name\"")
	}
	if _, ok := cc.mutation.Value(); !ok {
		return nil, errors.New("ent: missing required field \"value\"")
	}
	if v, ok := cc.mutation.Value(); ok {
		if err := contact.ValueValidator(v); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"value\": %v", err)
		}
	}
	if _, ok := cc.mutation.Kind(); !ok {
		v := contact.DefaultKind
		cc.mutation.SetKind(v)
	}
	if v, ok := cc.mutation.Kind(); ok {
		if err := contact.KindValidator(v); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"kind\": %v", err)
		}
	}
	if _, ok := cc.mutation.Principal(); !ok {
		return nil, errors.New("ent: missing required field \"principal\"")
	}
	if _, ok := cc.mutation.Validated(); !ok {
		return nil, errors.New("ent: missing required field \"validated\"")
	}
	if _, ok := cc.mutation.FromAccount(); !ok {
		v := contact.DefaultFromAccount
		cc.mutation.SetFromAccount(v)
	}
	if _, ok := cc.mutation.OwnerID(); !ok {
		return nil, errors.New("ent: missing required edge \"owner\"")
	}
	var (
		err  error
		node *Contact
	)
	if len(cc.hooks) == 0 {
		node, err = cc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ContactMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cc.mutation = mutation
			node, err = cc.sqlSave(ctx)
			return node, err
		})
		for i := len(cc.hooks) - 1; i >= 0; i-- {
			mut = cc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ContactCreate) SaveX(ctx context.Context) *Contact {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cc *ContactCreate) sqlSave(ctx context.Context) (*Contact, error) {
	var (
		c     = &Contact{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: contact.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: contact.FieldID,
			},
		}
	)
	if id, ok := cc.mutation.ID(); ok {
		c.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: contact.FieldName,
		})
		c.Name = value
	}
	if value, ok := cc.mutation.Value(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: contact.FieldValue,
		})
		c.Value = value
	}
	if value, ok := cc.mutation.Kind(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: contact.FieldKind,
		})
		c.Kind = value
	}
	if value, ok := cc.mutation.Principal(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: contact.FieldPrincipal,
		})
		c.Principal = value
	}
	if value, ok := cc.mutation.Validated(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: contact.FieldValidated,
		})
		c.Validated = value
	}
	if value, ok := cc.mutation.FromAccount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: contact.FieldFromAccount,
		})
		c.FromAccount = value
	}
	if nodes := cc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contact.OwnerTable,
			Columns: []string{contact.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: person.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return c, nil
}
