// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/google/uuid"
	"github.com/minskylab/collecta/ent/domain"
	"github.com/minskylab/collecta/ent/predicate"
	"github.com/minskylab/collecta/ent/survey"
	"github.com/minskylab/collecta/ent/user"
)

// DomainUpdate is the builder for updating Domain entities.
type DomainUpdate struct {
	config
	name           *string
	email          *string
	domain         *string
	collectaDomain *string
	tags           *[]string
	surveys        map[uuid.UUID]struct{}
	users          map[uuid.UUID]struct{}
	admins         map[uuid.UUID]struct{}
	removedSurveys map[uuid.UUID]struct{}
	removedUsers   map[uuid.UUID]struct{}
	removedAdmins  map[uuid.UUID]struct{}
	predicates     []predicate.Domain
}

// Where adds a new predicate for the builder.
func (du *DomainUpdate) Where(ps ...predicate.Domain) *DomainUpdate {
	du.predicates = append(du.predicates, ps...)
	return du
}

// SetName sets the name field.
func (du *DomainUpdate) SetName(s string) *DomainUpdate {
	du.name = &s
	return du
}

// SetEmail sets the email field.
func (du *DomainUpdate) SetEmail(s string) *DomainUpdate {
	du.email = &s
	return du
}

// SetDomain sets the domain field.
func (du *DomainUpdate) SetDomain(s string) *DomainUpdate {
	du.domain = &s
	return du
}

// SetCollectaDomain sets the collectaDomain field.
func (du *DomainUpdate) SetCollectaDomain(s string) *DomainUpdate {
	du.collectaDomain = &s
	return du
}

// SetTags sets the tags field.
func (du *DomainUpdate) SetTags(s []string) *DomainUpdate {
	du.tags = &s
	return du
}

// AddSurveyIDs adds the surveys edge to Survey by ids.
func (du *DomainUpdate) AddSurveyIDs(ids ...uuid.UUID) *DomainUpdate {
	if du.surveys == nil {
		du.surveys = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		du.surveys[ids[i]] = struct{}{}
	}
	return du
}

// AddSurveys adds the surveys edges to Survey.
func (du *DomainUpdate) AddSurveys(s ...*Survey) *DomainUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return du.AddSurveyIDs(ids...)
}

// AddUserIDs adds the users edge to User by ids.
func (du *DomainUpdate) AddUserIDs(ids ...uuid.UUID) *DomainUpdate {
	if du.users == nil {
		du.users = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		du.users[ids[i]] = struct{}{}
	}
	return du
}

// AddUsers adds the users edges to User.
func (du *DomainUpdate) AddUsers(u ...*User) *DomainUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return du.AddUserIDs(ids...)
}

// AddAdminIDs adds the admins edge to User by ids.
func (du *DomainUpdate) AddAdminIDs(ids ...uuid.UUID) *DomainUpdate {
	if du.admins == nil {
		du.admins = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		du.admins[ids[i]] = struct{}{}
	}
	return du
}

// AddAdmins adds the admins edges to User.
func (du *DomainUpdate) AddAdmins(u ...*User) *DomainUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return du.AddAdminIDs(ids...)
}

// RemoveSurveyIDs removes the surveys edge to Survey by ids.
func (du *DomainUpdate) RemoveSurveyIDs(ids ...uuid.UUID) *DomainUpdate {
	if du.removedSurveys == nil {
		du.removedSurveys = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		du.removedSurveys[ids[i]] = struct{}{}
	}
	return du
}

// RemoveSurveys removes surveys edges to Survey.
func (du *DomainUpdate) RemoveSurveys(s ...*Survey) *DomainUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return du.RemoveSurveyIDs(ids...)
}

// RemoveUserIDs removes the users edge to User by ids.
func (du *DomainUpdate) RemoveUserIDs(ids ...uuid.UUID) *DomainUpdate {
	if du.removedUsers == nil {
		du.removedUsers = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		du.removedUsers[ids[i]] = struct{}{}
	}
	return du
}

// RemoveUsers removes users edges to User.
func (du *DomainUpdate) RemoveUsers(u ...*User) *DomainUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return du.RemoveUserIDs(ids...)
}

// RemoveAdminIDs removes the admins edge to User by ids.
func (du *DomainUpdate) RemoveAdminIDs(ids ...uuid.UUID) *DomainUpdate {
	if du.removedAdmins == nil {
		du.removedAdmins = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		du.removedAdmins[ids[i]] = struct{}{}
	}
	return du
}

// RemoveAdmins removes admins edges to User.
func (du *DomainUpdate) RemoveAdmins(u ...*User) *DomainUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return du.RemoveAdminIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (du *DomainUpdate) Save(ctx context.Context) (int, error) {
	if du.name != nil {
		if err := domain.NameValidator(*du.name); err != nil {
			return 0, fmt.Errorf("ent: validator failed for field \"name\": %v", err)
		}
	}
	if du.email != nil {
		if err := domain.EmailValidator(*du.email); err != nil {
			return 0, fmt.Errorf("ent: validator failed for field \"email\": %v", err)
		}
	}
	return du.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DomainUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DomainUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DomainUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

func (du *DomainUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   domain.Table,
			Columns: domain.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: domain.FieldID,
			},
		},
	}
	if ps := du.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value := du.name; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: domain.FieldName,
		})
	}
	if value := du.email; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: domain.FieldEmail,
		})
	}
	if value := du.domain; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: domain.FieldDomain,
		})
	}
	if value := du.collectaDomain; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: domain.FieldCollectaDomain,
		})
	}
	if value := du.tags; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  *value,
			Column: domain.FieldTags,
		})
	}
	if nodes := du.removedSurveys; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domain.SurveysTable,
			Columns: []string{domain.SurveysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: survey.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.surveys; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domain.SurveysTable,
			Columns: []string{domain.SurveysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: survey.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := du.removedUsers; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   domain.UsersTable,
			Columns: domain.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.users; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   domain.UsersTable,
			Columns: domain.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := du.removedAdmins; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   domain.AdminsTable,
			Columns: domain.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.admins; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   domain.AdminsTable,
			Columns: domain.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{domain.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// DomainUpdateOne is the builder for updating a single Domain entity.
type DomainUpdateOne struct {
	config
	id             uuid.UUID
	name           *string
	email          *string
	domain         *string
	collectaDomain *string
	tags           *[]string
	surveys        map[uuid.UUID]struct{}
	users          map[uuid.UUID]struct{}
	admins         map[uuid.UUID]struct{}
	removedSurveys map[uuid.UUID]struct{}
	removedUsers   map[uuid.UUID]struct{}
	removedAdmins  map[uuid.UUID]struct{}
}

// SetName sets the name field.
func (duo *DomainUpdateOne) SetName(s string) *DomainUpdateOne {
	duo.name = &s
	return duo
}

// SetEmail sets the email field.
func (duo *DomainUpdateOne) SetEmail(s string) *DomainUpdateOne {
	duo.email = &s
	return duo
}

// SetDomain sets the domain field.
func (duo *DomainUpdateOne) SetDomain(s string) *DomainUpdateOne {
	duo.domain = &s
	return duo
}

// SetCollectaDomain sets the collectaDomain field.
func (duo *DomainUpdateOne) SetCollectaDomain(s string) *DomainUpdateOne {
	duo.collectaDomain = &s
	return duo
}

// SetTags sets the tags field.
func (duo *DomainUpdateOne) SetTags(s []string) *DomainUpdateOne {
	duo.tags = &s
	return duo
}

// AddSurveyIDs adds the surveys edge to Survey by ids.
func (duo *DomainUpdateOne) AddSurveyIDs(ids ...uuid.UUID) *DomainUpdateOne {
	if duo.surveys == nil {
		duo.surveys = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		duo.surveys[ids[i]] = struct{}{}
	}
	return duo
}

// AddSurveys adds the surveys edges to Survey.
func (duo *DomainUpdateOne) AddSurveys(s ...*Survey) *DomainUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return duo.AddSurveyIDs(ids...)
}

// AddUserIDs adds the users edge to User by ids.
func (duo *DomainUpdateOne) AddUserIDs(ids ...uuid.UUID) *DomainUpdateOne {
	if duo.users == nil {
		duo.users = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		duo.users[ids[i]] = struct{}{}
	}
	return duo
}

// AddUsers adds the users edges to User.
func (duo *DomainUpdateOne) AddUsers(u ...*User) *DomainUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return duo.AddUserIDs(ids...)
}

// AddAdminIDs adds the admins edge to User by ids.
func (duo *DomainUpdateOne) AddAdminIDs(ids ...uuid.UUID) *DomainUpdateOne {
	if duo.admins == nil {
		duo.admins = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		duo.admins[ids[i]] = struct{}{}
	}
	return duo
}

// AddAdmins adds the admins edges to User.
func (duo *DomainUpdateOne) AddAdmins(u ...*User) *DomainUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return duo.AddAdminIDs(ids...)
}

// RemoveSurveyIDs removes the surveys edge to Survey by ids.
func (duo *DomainUpdateOne) RemoveSurveyIDs(ids ...uuid.UUID) *DomainUpdateOne {
	if duo.removedSurveys == nil {
		duo.removedSurveys = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		duo.removedSurveys[ids[i]] = struct{}{}
	}
	return duo
}

// RemoveSurveys removes surveys edges to Survey.
func (duo *DomainUpdateOne) RemoveSurveys(s ...*Survey) *DomainUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return duo.RemoveSurveyIDs(ids...)
}

// RemoveUserIDs removes the users edge to User by ids.
func (duo *DomainUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *DomainUpdateOne {
	if duo.removedUsers == nil {
		duo.removedUsers = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		duo.removedUsers[ids[i]] = struct{}{}
	}
	return duo
}

// RemoveUsers removes users edges to User.
func (duo *DomainUpdateOne) RemoveUsers(u ...*User) *DomainUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return duo.RemoveUserIDs(ids...)
}

// RemoveAdminIDs removes the admins edge to User by ids.
func (duo *DomainUpdateOne) RemoveAdminIDs(ids ...uuid.UUID) *DomainUpdateOne {
	if duo.removedAdmins == nil {
		duo.removedAdmins = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		duo.removedAdmins[ids[i]] = struct{}{}
	}
	return duo
}

// RemoveAdmins removes admins edges to User.
func (duo *DomainUpdateOne) RemoveAdmins(u ...*User) *DomainUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return duo.RemoveAdminIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (duo *DomainUpdateOne) Save(ctx context.Context) (*Domain, error) {
	if duo.name != nil {
		if err := domain.NameValidator(*duo.name); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"name\": %v", err)
		}
	}
	if duo.email != nil {
		if err := domain.EmailValidator(*duo.email); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"email\": %v", err)
		}
	}
	return duo.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DomainUpdateOne) SaveX(ctx context.Context) *Domain {
	d, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return d
}

// Exec executes the query on the entity.
func (duo *DomainUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DomainUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (duo *DomainUpdateOne) sqlSave(ctx context.Context) (d *Domain, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   domain.Table,
			Columns: domain.Columns,
			ID: &sqlgraph.FieldSpec{
				Value:  duo.id,
				Type:   field.TypeUUID,
				Column: domain.FieldID,
			},
		},
	}
	if value := duo.name; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: domain.FieldName,
		})
	}
	if value := duo.email; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: domain.FieldEmail,
		})
	}
	if value := duo.domain; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: domain.FieldDomain,
		})
	}
	if value := duo.collectaDomain; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: domain.FieldCollectaDomain,
		})
	}
	if value := duo.tags; value != nil {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  *value,
			Column: domain.FieldTags,
		})
	}
	if nodes := duo.removedSurveys; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domain.SurveysTable,
			Columns: []string{domain.SurveysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: survey.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.surveys; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   domain.SurveysTable,
			Columns: []string{domain.SurveysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: survey.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := duo.removedUsers; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   domain.UsersTable,
			Columns: domain.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.users; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   domain.UsersTable,
			Columns: domain.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := duo.removedAdmins; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   domain.AdminsTable,
			Columns: domain.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.admins; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   domain.AdminsTable,
			Columns: domain.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	d = &Domain{config: duo.config}
	_spec.Assign = d.assignValues
	_spec.ScanValues = d.scanValues()
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{domain.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return d, nil
}
