// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/google/uuid"
	"github.com/minskylab/collecta/ent/answer"
	"github.com/minskylab/collecta/ent/flow"
	"github.com/minskylab/collecta/ent/input"
	"github.com/minskylab/collecta/ent/question"
)

// QuestionCreate is the builder for creating a Question entity.
type QuestionCreate struct {
	config
	mutation *QuestionMutation
	hooks    []Hook
}

// SetHash sets the hash field.
func (qc *QuestionCreate) SetHash(s string) *QuestionCreate {
	qc.mutation.SetHash(s)
	return qc
}

// SetTitle sets the title field.
func (qc *QuestionCreate) SetTitle(s string) *QuestionCreate {
	qc.mutation.SetTitle(s)
	return qc
}

// SetDescription sets the description field.
func (qc *QuestionCreate) SetDescription(s string) *QuestionCreate {
	qc.mutation.SetDescription(s)
	return qc
}

// SetMetadata sets the metadata field.
func (qc *QuestionCreate) SetMetadata(m map[string]interface{}) *QuestionCreate {
	qc.mutation.SetMetadata(m)
	return qc
}

// SetValidator sets the validator field.
func (qc *QuestionCreate) SetValidator(s string) *QuestionCreate {
	qc.mutation.SetValidator(s)
	return qc
}

// SetNillableValidator sets the validator field if the given value is not nil.
func (qc *QuestionCreate) SetNillableValidator(s *string) *QuestionCreate {
	if s != nil {
		qc.SetValidator(*s)
	}
	return qc
}

// SetAnonymous sets the anonymous field.
func (qc *QuestionCreate) SetAnonymous(b bool) *QuestionCreate {
	qc.mutation.SetAnonymous(b)
	return qc
}

// SetNillableAnonymous sets the anonymous field if the given value is not nil.
func (qc *QuestionCreate) SetNillableAnonymous(b *bool) *QuestionCreate {
	if b != nil {
		qc.SetAnonymous(*b)
	}
	return qc
}

// SetID sets the id field.
func (qc *QuestionCreate) SetID(u uuid.UUID) *QuestionCreate {
	qc.mutation.SetID(u)
	return qc
}

// AddAnswerIDs adds the answers edge to Answer by ids.
func (qc *QuestionCreate) AddAnswerIDs(ids ...uuid.UUID) *QuestionCreate {
	qc.mutation.AddAnswerIDs(ids...)
	return qc
}

// AddAnswers adds the answers edges to Answer.
func (qc *QuestionCreate) AddAnswers(a ...*Answer) *QuestionCreate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return qc.AddAnswerIDs(ids...)
}

// SetInputID sets the input edge to Input by id.
func (qc *QuestionCreate) SetInputID(id uuid.UUID) *QuestionCreate {
	qc.mutation.SetInputID(id)
	return qc
}

// SetNillableInputID sets the input edge to Input by id if the given value is not nil.
func (qc *QuestionCreate) SetNillableInputID(id *uuid.UUID) *QuestionCreate {
	if id != nil {
		qc = qc.SetInputID(*id)
	}
	return qc
}

// SetInput sets the input edge to Input.
func (qc *QuestionCreate) SetInput(i *Input) *QuestionCreate {
	return qc.SetInputID(i.ID)
}

// SetFlowID sets the flow edge to Flow by id.
func (qc *QuestionCreate) SetFlowID(id uuid.UUID) *QuestionCreate {
	qc.mutation.SetFlowID(id)
	return qc
}

// SetNillableFlowID sets the flow edge to Flow by id if the given value is not nil.
func (qc *QuestionCreate) SetNillableFlowID(id *uuid.UUID) *QuestionCreate {
	if id != nil {
		qc = qc.SetFlowID(*id)
	}
	return qc
}

// SetFlow sets the flow edge to Flow.
func (qc *QuestionCreate) SetFlow(f *Flow) *QuestionCreate {
	return qc.SetFlowID(f.ID)
}

// Save creates the Question in the database.
func (qc *QuestionCreate) Save(ctx context.Context) (*Question, error) {
	if _, ok := qc.mutation.Hash(); !ok {
		return nil, errors.New("ent: missing required field \"hash\"")
	}
	if _, ok := qc.mutation.Title(); !ok {
		return nil, errors.New("ent: missing required field \"title\"")
	}
	if v, ok := qc.mutation.Title(); ok {
		if err := question.TitleValidator(v); err != nil {
			return nil, fmt.Errorf("ent: validator failed for field \"title\": %v", err)
		}
	}
	if _, ok := qc.mutation.Description(); !ok {
		return nil, errors.New("ent: missing required field \"description\"")
	}
	if _, ok := qc.mutation.Anonymous(); !ok {
		v := question.DefaultAnonymous
		qc.mutation.SetAnonymous(v)
	}
	var (
		err  error
		node *Question
	)
	if len(qc.hooks) == 0 {
		node, err = qc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QuestionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			qc.mutation = mutation
			node, err = qc.sqlSave(ctx)
			return node, err
		})
		for i := len(qc.hooks) - 1; i >= 0; i-- {
			mut = qc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, qc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (qc *QuestionCreate) SaveX(ctx context.Context) *Question {
	v, err := qc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (qc *QuestionCreate) sqlSave(ctx context.Context) (*Question, error) {
	var (
		q     = &Question{config: qc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: question.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: question.FieldID,
			},
		}
	)
	if id, ok := qc.mutation.ID(); ok {
		q.ID = id
		_spec.ID.Value = id
	}
	if value, ok := qc.mutation.Hash(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: question.FieldHash,
		})
		q.Hash = value
	}
	if value, ok := qc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: question.FieldTitle,
		})
		q.Title = value
	}
	if value, ok := qc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: question.FieldDescription,
		})
		q.Description = value
	}
	if value, ok := qc.mutation.Metadata(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: question.FieldMetadata,
		})
		q.Metadata = value
	}
	if value, ok := qc.mutation.Validator(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: question.FieldValidator,
		})
		q.Validator = value
	}
	if value, ok := qc.mutation.Anonymous(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: question.FieldAnonymous,
		})
		q.Anonymous = value
	}
	if nodes := qc.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.AnswersTable,
			Columns: []string{question.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: answer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := qc.mutation.InputIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   question.InputTable,
			Columns: []string{question.InputColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: input.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := qc.mutation.FlowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   question.FlowTable,
			Columns: []string{question.FlowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: flow.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if err := sqlgraph.CreateNode(ctx, qc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return q, nil
}
