// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/minskylab/collecta/ent/predicate"
	"github.com/minskylab/collecta/ent/short"
)

// ShortUpdate is the builder for updating Short entities.
type ShortUpdate struct {
	config

	predicates []predicate.Short
}

// Where adds a new predicate for the builder.
func (su *ShortUpdate) Where(ps ...predicate.Short) *ShortUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *ShortUpdate) Save(ctx context.Context) (int, error) {
	return su.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (su *ShortUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ShortUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ShortUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *ShortUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   short.Table,
			Columns: short.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: short.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{short.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ShortUpdateOne is the builder for updating a single Short entity.
type ShortUpdateOne struct {
	config
	id int
}

// Save executes the query and returns the updated entity.
func (suo *ShortUpdateOne) Save(ctx context.Context) (*Short, error) {
	return suo.sqlSave(ctx)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ShortUpdateOne) SaveX(ctx context.Context) *Short {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *ShortUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ShortUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *ShortUpdateOne) sqlSave(ctx context.Context) (s *Short, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   short.Table,
			Columns: short.Columns,
			ID: &sqlgraph.FieldSpec{
				Value:  suo.id,
				Type:   field.TypeInt,
				Column: short.FieldID,
			},
		},
	}
	s = &Short{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{short.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
