// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/minskylab/collecta/ent/short"
	"github.com/minskylab/collecta/uuid"
)

// Short is the model entity for the Short schema.
type Short struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Value holds the value of the "value" field.
	Value uuid.UUID `json:"value,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Short) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // key
		&uuid.UUID{},      // value
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Short fields.
func (s *Short) assignValues(values ...interface{}) error {
	if m, n := len(values), len(short.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field key", values[0])
	} else if value.Valid {
		s.Key = value.String
	}
	if value, ok := values[1].(*uuid.UUID); !ok {
		return fmt.Errorf("unexpected type %T for field value", values[1])
	} else if value != nil {
		s.Value = *value
	}
	return nil
}

// Update returns a builder for updating this Short.
// Note that, you need to call Short.Unwrap() before calling this method, if this Short
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Short) Update() *ShortUpdateOne {
	return (&ShortClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Short) Unwrap() *Short {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Short is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Short) String() string {
	var builder strings.Builder
	builder.WriteString("Short(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", key=")
	builder.WriteString(s.Key)
	builder.WriteString(", value=")
	builder.WriteString(fmt.Sprintf("%v", s.Value))
	builder.WriteByte(')')
	return builder.String()
}

// Shorts is a parsable slice of Short.
type Shorts []*Short

func (s Shorts) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
