mutation {
    addSurvey(
        input: [
            {
                title: "Text Survey"
                spans: [{ where: BEFORE, at: "start", text: "Hello, please give a feedback" }]
                questions: [
                    {
                        order: 0
                        hash: "04e35eb3e4fcb8b395191053c359ca0e"
                        title: "How are you?"
                        anonymous: false
                        input: [{ id: "0x2" }]
                    }
                ]
            }
        ]
    ) {
        survey {
            id
        }
    }
}
