// Code generated by entc, DO NOT EDIT.

package shorts

import (
	"github.com/minskylab/collecta/ent/schema"
)

const (
	// Label holds the string label denoting the shorts type in the database.
	Label = "shorts"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key vertex property in the database.
	FieldKey = "key"
	// FieldValue holds the string denoting the value vertex property in the database.
	FieldValue = "value"

	// Table holds the table name of the shorts in the database.
	Table = "shorts"
)

// Columns holds all SQL columns for shorts fields.
var Columns = []string{
	FieldID,
	FieldKey,
	FieldValue,
}

var (
	fields = schema.Shorts{}.Fields()

	// descKey is the schema descriptor for key field.
	descKey = fields[0].Descriptor()
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator = descKey.Validators[0].(func(string) error)
)
