// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Answer is the predicate function for answer builders.
type Answer func(*sql.Selector)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// Domain is the predicate function for domain builders.
type Domain func(*sql.Selector)

// Flow is the predicate function for flow builders.
type Flow func(*sql.Selector)

// IP is the predicate function for ip builders.
type IP func(*sql.Selector)

// Input is the predicate function for input builders.
type Input func(*sql.Selector)

// Person is the predicate function for person builders.
type Person func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)

// Short is the predicate function for short builders.
type Short func(*sql.Selector)

// Survey is the predicate function for survey builders.
type Survey func(*sql.Selector)
